version: "3"

services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=contacts_db_user
      - MONGO_INITDB_ROOT_PASSWORD=S3cret

  rabbitmq:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=contacts_queue_user
      - RABBITMQ_DEFAULT_PASS=S3cret